version: '3.8'

services:
  backend:
    build:
      dockerfile: build/Dockerfile
      context: ..
    restart: unless-stopped
    ports:
      - '3000:3000'

  redis:
    container_name: redis
    hostname: redis
    image: redis
    restart: always
    command: [ 'redis-server', '--save', '20', '1' ]
    expose:
      - '6379'
    volumes:
      - redis:/data

volumes:
  redis: